CREATE TABLE USR
(
UID NUMBER PRIMARY KEY,
USERNAME VARCHAR(20) UNIQUE,
PWD VARCHAR(20) UNIQUE,
UNAME VARCHAR(20) NOT NULL
);

CREATE TABLE ADM
(
AID NUMBER PRIMARY KEY,
USERNAME VARCHAR(20) UNIQUE,
PWD VARCHAR(20) UNIQUE,
ANAME VARCHAR(20) NOT NULL
);

CREATE TABLE QUIZ 
(
QID NUMBER PRIMARY KEY,
GENRE VARCHAR(15) NOT NULL,
DATECREATED DATE,
AID NUMBER,
FOREIGN KEY (AID) REFERENCES ADM(AID)
);

CREATE TABLE USR
(
USRID NUMBER PRIMARY KEY,
USERNAME VARCHAR(20) UNIQUE,
PWD VARCHAR(20) UNIQUE,
NAME VARCHAR(20) NOT NULL
);

CREATE TABLE QUIZATTEMPTS
(
USRID NUMBER,
QID NUMBER,
SCORE NUMBER CHECK(SCORE BETWEEN 0 AND 5) NOT NULL,
DATEATTEMPT DATE,
PRIMARY KEY (USRID,QID),
FOREIGN KEY (USRID) REFERENCES USR(USRID),
FOREIGN KEY (QID) REFERENCES QUIZ(QID)
);

CREATE TABLE QUESTIONS
(
QID NUMBER,
QNO NUMBER,
QN VARCHAR(50) NOT NULL,
OPTA VARCHAR(30),
OPTB VARCHAR(30),
OPTC VARCHAR(30),
OPTD VARCHAR(30),
CRCTANS CHAR(1) CHECK(CRCTANS IN ('A','B','C','D')),
PRIMARY KEY(QID,QNO),
FOREIGN KEY (QID) REFERENCES QUIZ(QID)
);





